#!/usr/bin/env bash
#
# CaMeLz Variables
#
# The default live location of this file is ~/.camelz/variables. This is the version of this file which wil be used
# during the build process.
#
# Defaults and Examples of this script can be found in $CAMELZ_HOME/conf/:
# - variables.default - a default version of this file, containing an empty set of variables in build sequence.
# - variables.example - an example version of this file, containing the variables created when building the demo system.
#
# Source this script to rebuild your terminal environment variables if you need to restart your terminal session.
#
# The camelz-load shell function will source the constants script and this variables script
#
# Use the camelz-variable shell function to "upsert" keys in this file each time one is created or replaced.


## Organizations ######################################################################################################

## - CaMeLz Organization
org_id=
root_id=
security_ou_id=
infrastructure_ou_id=
sandbox_ou_id=
workloads_ou_id=
workloads_production_ou_id=
workloads_nonproduction_ou_id=
deployments_ou_id=
deployments_production_ou_id=


## Accounts ###########################################################################################################

## - CaMeLz Organization
management_account_id=
log_account_id=
audit_account_id=
network_account_id=
core_account_id=
build_account_id=
production_account_id=
recovery_account_id=
development_account_id=

## - Alfa Client
alfa_production_account_id=
alfa_recovery_account_id=
alfa_development_account_id=

## - Zulu Client
zulu_production_account_id=
zulu_development_account_id=


## Public Hosted Zones ################################################################################################

## Global (Virginia)
## - Global Public Hosted Zones
global_management_public_hostedzone_id=
global_log_public_hostedzone_id=
global_audit_public_hostedzone_id=
global_network_public_hostedzone_id=
global_core_public_hostedzone_id=
global_build_public_hostedzone_id=
global_production_public_hostedzone_id=
global_recovery_public_hostedzone_id=
global_staging_public_hostedzone_id=
global_testing_public_hostedzone_id=
global_development_public_hostedzone_id=

## Ohio
## - Ohio Public Hosted Zones
ohio_management_public_hostedzone_id=
ohio_log_public_hostedzone_id=
ohio_audit_public_hostedzone_id=
ohio_network_public_hostedzone_id=
ohio_core_public_hostedzone_id=
ohio_core_public_hostedzone_id=
ohio_build_public_hostedzone_id=
ohio_production_public_hostedzone_id=
ohio_recovery_public_hostedzone_id=
ohio_staging_public_hostedzone_id=
ohio_testing_public_hostedzone_id=
ohio_development_public_hostedzone_id=

## - Alfa Ohio Public Hosted Zones
alfa_ohio_production_public_hostedzone_id=
alfa_ohio_testing_public_hostedzone_id=
alfa_ohio_development_public_hostedzone_id=

## - Zulu Ohio Shared Public Hosted Zones
zulu_ohio_production_public_hostedzone_id=
zulu_ohio_development_public_hostedzone_id=

## Oregon
## - Oregon Public Hosted Zones
oregon_management_public_hostedzone_id=
oregon_audit_public_hostedzone_id=
oregon_core_public_hostedzone_id=

## - Alfa Oregon Public Hosted Zones
alfa_oregon_production_public_hostedzone_id=
alfa_oregon_recovery_public_hostedzone_id=

## Data Centers
## - Alfa LosAngeles
alfa_lax_public_hostedzone_id=
alfa_mia_public_hostedzone_id=

## - Alfa Miami
zulu_dfw_public_hostedzone_id=

## - CaMeLz SantaBarbara
cml_sba_public_hostedzone_id=


## VPCs ###############################################################################################################

## Global (Virginia)
## - Global Management VPC
global_management_vpc_id=
global_management_igw_id=
global_management_private_hostedzone_id=
global_management_dopt_id=
global_management_firewall_subneta_id=
global_management_firewall_subnetb_id=
global_management_firewall_subnetc_id=
global_management_public_subneta_id=
global_management_public_subnetb_id=
global_management_public_subnetc_id=
global_management_web_subneta_id=
global_management_web_subnetb_id=
global_management_web_subnetc_id=
global_management_application_subneta_id=
global_management_application_subnetb_id=
global_management_application_subnetc_id=
global_management_database_subneta_id=
global_management_database_subnetb_id=
global_management_database_subnetc_id=
global_management_directory_subneta_id=
global_management_directory_subnetb_id=
global_management_directory_subnetc_id=
global_management_management_subneta_id=
global_management_management_subnetb_id=
global_management_management_subnetc_id=
global_management_gateway_subneta_id=
global_management_gateway_subnetb_id=
global_management_gateway_subnetc_id=
global_management_endpoint_subneta_id=
global_management_endpoint_subnetb_id=
global_management_endpoint_subnetc_id=
global_management_public_rtb_id=
global_management_ngw_eipa=
global_management_ngwa_id=
global_management_ngw_eipb=
global_management_ngwb_id=
global_management_ngw_eipc=
global_management_ngwc_id=
global_management_nat_sg_id=
global_management_nat_instance_id=
global_management_nat_instance_eni_id=
global_management_nat_instance_private_ip=
global_management_private_rtba_id=
global_management_private_rtbb_id=
global_management_private_rtbc_id=
global_management_vpce_sg_id=
global_management_ssm_vpce_id=
global_management_ssmm_vpce_id=

## - Global Core VPC
global_core_vpc_id=
global_core_igw_id=
global_core_private_hostedzone_id=
global_core_dopt_id=
global_core_firewall_subneta_id=
global_core_firewall_subnetb_id=
global_core_firewall_subnetc_id=
global_core_public_subneta_id=
global_core_public_subnetb_id=
global_core_public_subnetc_id=
global_core_web_subneta_id=
global_core_web_subnetb_id=
global_core_web_subnetc_id=
global_core_application_subneta_id=
global_core_application_subnetb_id=
global_core_application_subnetc_id=
global_core_database_subneta_id=
global_core_database_subnetb_id=
global_core_database_subnetc_id=
global_core_management_subneta_id=
global_core_management_subnetb_id=
global_core_management_subnetc_id=
global_core_gateway_subneta_id=
global_core_gateway_subnetb_id=
global_core_gateway_subnetc_id=
global_core_endpoint_subneta_id=
global_core_endpoint_subnetb_id=
global_core_endpoint_subnetc_id=
global_core_public_rtb_id=
global_core_ngw_eipa=
global_core_ngwa_id=
global_core_ngw_eipb=
global_core_ngwb_id=
global_core_ngw_eipc=
global_core_ngwc_id=
global_core_nat_sg_id=
global_core_nat_instance_id=
global_core_nat_instance_eni_id=
global_core_nat_instance_private_ip=
global_core_private_rtba_id=
global_core_private_rtbb_id=
global_core_private_rtbc_id=
global_core_vpce_sg_id=
global_core_ssm_vpce_id=
global_core_ssmm_vpce_id=

## Ohio
## - Ohio Management VPC
ohio_management_vpc_id=
ohio_management_igw_id=
ohio_management_private_hostedzone_id=
ohio_management_dopt_id=
ohio_management_firewall_subneta_id=
ohio_management_firewall_subnetb_id=
ohio_management_firewall_subnetc_id=
ohio_management_public_subneta_id=
ohio_management_public_subnetb_id=
ohio_management_public_subnetc_id=
ohio_management_web_subneta_id=
ohio_management_web_subnetb_id=
ohio_management_web_subnetc_id=
ohio_management_application_subneta_id=
ohio_management_application_subnetb_id=
ohio_management_application_subnetc_id=
ohio_management_database_subneta_id=
ohio_management_database_subnetb_id=
ohio_management_database_subnetc_id=
ohio_management_directory_subneta_id=
ohio_management_directory_subnetb_id=
ohio_management_directory_subnetc_id=
ohio_management_management_subneta_id=
ohio_management_management_subnetb_id=
ohio_management_management_subnetc_id=
ohio_management_gateway_subneta_id=
ohio_management_gateway_subnetb_id=
ohio_management_gateway_subnetc_id=
ohio_management_endpoint_subneta_id=
ohio_management_endpoint_subnetb_id=
ohio_management_endpoint_subnetc_id=
ohio_management_public_rtb_id=
ohio_management_ngw_eipa=
ohio_management_ngwa_id=
ohio_management_ngw_eipb=
ohio_management_ngwb_id=
ohio_management_ngw_eipc=
ohio_management_ngwc_id=
ohio_management_nat_sg_id=
ohio_management_nat_instance_id=
ohio_management_nat_instance_eni_id=
ohio_management_nat_instance_private_ip=
ohio_management_private_rtba_id=
ohio_management_private_rtbb_id=
ohio_management_private_rtbc_id=
ohio_management_vpce_sg_id=
ohio_management_ssm_vpce_id=
ohio_management_ssmm_vpce_id=

## - Ohio Core VPC
ohio_core_vpc_id=
ohio_core_igw_id=
ohio_core_private_hostedzone_id=
ohio_core_dopt_id=
ohio_core_firewall_subneta_id=
ohio_core_firewall_subnetb_id=
ohio_core_firewall_subnetc_id=
ohio_core_public_subneta_id=
ohio_core_public_subnetb_id=
ohio_core_public_subnetc_id=
ohio_core_web_subneta_id=
ohio_core_web_subnetb_id=
ohio_core_web_subnetc_id=
ohio_core_application_subneta_id=
ohio_core_application_subnetb_id=
ohio_core_application_subnetc_id=
ohio_core_database_subneta_id=
ohio_core_database_subnetb_id=
ohio_core_database_subnetc_id=
ohio_core_management_subneta_id=
ohio_core_management_subnetb_id=
ohio_core_management_subnetc_id=
ohio_core_gateway_subneta_id=
ohio_core_gateway_subnetb_id=
ohio_core_gateway_subnetc_id=
ohio_core_endpoint_subneta_id=
ohio_core_endpoint_subnetb_id=
ohio_core_endpoint_subnetc_id=
ohio_core_public_rtb_id=
ohio_core_ngw_eipa=
ohio_core_ngwa_id=
ohio_core_ngw_eipb=
ohio_core_ngwb_id=
ohio_core_ngw_eipc=
ohio_core_ngwc_id=
ohio_core_nat_sg_id=
ohio_core_nat_instance_id=
ohio_core_nat_instance_eni_id=
ohio_core_nat_instance_private_ip=
ohio_core_private_rtba_id=
ohio_core_private_rtbb_id=
ohio_core_private_rtbc_id=
ohio_core_vpce_sg_id=
ohio_core_ssm_vpce_id=
ohio_core_ssmm_vpce_id=
